// Design tokens — keep in sync with theme.css :root variables
export const theme = {
  brand: '#00C7D2',
  brandHover: '#00b3bd',
  brandBg: '#e6fafb',
  textPrimary: '#000000',
  textSecondary: '#4D4D4D',
  textTertiary: '#808080',
  textPlaceholder: '#B2B2B2',
  colorPositive: '#00C7D2',
  colorPositiveBg: '#e6fafb',
  colorWarning: '#ca8a04',
  colorWarningBg: '#fef9c3',
  colorStopped: '#9CA3AF',
  colorStoppedBg: '#F3F4F6',
  colorDead: '#D1D5DB',
  colorDeadBg: '#F9FAFB',
  colorError: '#dc2626',
  colorErrorBg: '#FEF2F2',
  colorDeployed: '#0081f2',
  colorDeployedBg: '#dbeafe',
  bg: '#f8f8f7',
  surface: '#fff',
  border: '#ebebeb',
  radius: '16px',
} as const;
